"""scicodewiki command-line entry."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _repo_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--repo", default=".",
                        help="target repository root (default: cwd)")
    parser.add_argument("--formulas", default=None,
                        help="formulas dir (default: <repo>/formulas)")


def _cmd_verify(args) -> int:
    import os

    from .drift import head_commit
    from .verify import verify_repo

    repo = Path(args.repo).resolve()
    # formula_impl modules locate the target package through this
    os.environ["SCICODEWIKI_REPO"] = str(repo)
    formulas = Path(args.formulas) if args.formulas else repo / "wiki" / "formulas"
    commit = head_commit(repo) or "nogit"
    results = verify_repo(formulas, commit=commit, seed=args.seed,
                          only=args.entry, record=args.record)
    if not results:
        print(f"scicodewiki: no entries under {formulas}", file=sys.stderr)
        return 2
    failed = 0
    for entry, verdict in results:
        line = f"{entry.id}: {verdict.result}"
        if verdict.diagnosis:
            line += f" -- {verdict.diagnosis}"
        print(line)
        failed += verdict.result == "fail"
    return 1 if failed else 0


def _cmd_preview(args) -> int:
    import tempfile

    import yaml as _yaml

    from .census import preview_manifest, scan_package
    from .render import build

    repo = Path(args.repo).resolve()
    if (repo / "wiki" / "formulas").exists() and not args.force:
        print("scicodewiki: registry exists at wiki/formulas — use `build` "
              "for the full wiki; preview is the zero-setup funnel entry "
              "(--force to overwrite)", file=sys.stderr)
        return 2
    census = scan_package(repo, args.package or repo.name)
    manifest = preview_manifest(census, repo.name)
    with tempfile.TemporaryDirectory() as td:
        fdir = Path(td)
        (fdir / "manifest.yaml").write_text(
            _yaml.safe_dump(manifest, allow_unicode=True, sort_keys=False),
            encoding="utf-8")
        build(repo, fdir, repo / "wiki")
    print(f"preview wiki at {repo / 'wiki'}: code-layer navigation only, "
          f"no formula layer; bootstrap+extract+narrate+build for the "
          f"verified wiki")
    return 0


def _cmd_lint(args) -> int:
    from .lint import lint_narratives

    problems = lint_narratives(Path(args.repo).resolve() / "wiki" / "narratives")
    for prob in problems:
        print(prob)
    print(f"lint: {len(problems)} problems (0 = chapter-spec discipline holds)")
    return 1 if problems else 0


def _cmd_census(args) -> int:
    from .census import write_census

    repo = Path(args.repo).resolve()
    package = args.package or repo.name
    out = repo / "wiki" / ".census.json"
    census = write_census(repo, package, out)
    print(f"{len(census['units'])} modules, "
          f"{sum(len(u['functions']) for u in census['units'])} functions "
          f"-> {out}")
    return 0


def _cmd_coverage(args) -> int:
    from .census import scan_package, undocumented
    from .manifest import load_manifest

    from .census import over_budget
    from .registry import load_entries

    repo = Path(args.repo).resolve()
    package = args.package or repo.name
    formulas = repo / "wiki" / "formulas"
    manifest = load_manifest(formulas / "manifest.yaml")
    census = scan_package(repo, package)
    gaps = undocumented(census, manifest)
    for u in gaps:
        print(f"undocumented: {u['module']} ({u['loc']} LOC, "
              f"{len(u['functions'])} funcs)")
    entries = load_entries(formulas) if (formulas).is_dir() else []
    for h in over_budget(census, manifest, entries):
        where = f"{h['stage']}/{h['page']}" if h["page"] else h["stage"]
        print(f"over-budget: {where} binds {h['loc']} LOC (>1500: "
              f"split + bottom-up synthesis per chapter-spec)")
    print(f"coverage: {len(gaps)} undocumented modules "
          f"(0 = every census unit is documented)")
    return 0


def _cmd_clean(args) -> int:
    """Wipe ALL scicodewiki outputs (the whole wiki/) so every test is a
    from-scratch generation. The repo's own content (source, docs/, README,
    examples) is never touched; wiki/ is regenerated by
    bootstrap -> extract -> narrate -> build -> verify."""
    import shutil

    repo = Path(args.repo).resolve()
    wiki = repo / "wiki"
    if wiki.is_dir():
        shutil.rmtree(wiki)
        print(f"removed {wiki}")
    print("kept: repo source, docs/, README, examples (never generated)")
    return 0


def _cmd_serve(args) -> int:
    import subprocess

    repo = Path(args.repo).resolve()
    cfg = repo / "wiki" / "mkdocs.yml"
    if not cfg.exists():
        print("scicodewiki: no wiki/mkdocs.yml; run `scicodewiki build` first",
              file=sys.stderr)
        return 2
    return subprocess.call([sys.executable, "-m", "mkdocs", "serve",
                            "-f", str(cfg), "-a", args.addr])


def _cmd_build(args) -> int:
    from .render import build

    repo = Path(args.repo).resolve()
    formulas = Path(args.formulas) if args.formulas else repo / "wiki" / "formulas"
    out = Path(args.out) if args.out else repo / "wiki"
    for path in build(repo, formulas, out):
        print(path)
    return 0


CONVENTION_SECTION = """<!-- scicodewiki:conventions -->
## scicodewiki 约定

- 本仓库有 formulas/ 注册表：机器可验证的科学断言（公式/约定/文献）。
- 代码绑定清单：formulas/ 各 yaml 的 implements.file。
- 改动绑定代码后：跑 `scicodewiki verify --repo .`，处理 ❌ failing / 🕐 stale 徽章。
- wiki：`scicodewiki build`（输出 wiki/）。
<!-- /scicodewiki:conventions -->
"""


def _cmd_init(args) -> int:
    repo = Path(args.repo).resolve()
    formulas = repo / "wiki" / "formulas"
    formulas.mkdir(parents=True, exist_ok=True)
    manifest = formulas / "manifest.yaml"
    if not manifest.exists():
        manifest.write_text(f"repo: {repo.name}\nstages: []\n",
                            encoding="utf-8")
        print(f"created {manifest}")
    if not args.agents_md:
        print("skip AGENTS.md/CLAUDE.md injection "
              "(pass --agents-md to opt in; default footprint stays in wiki/)")
        return 0
    for name in ("AGENTS.md", "CLAUDE.md"):
        target = repo / name
        existing = target.read_text(encoding="utf-8") if target.exists() else ""
        if "scicodewiki:conventions" in existing:
            print(f"{name}: conventions already present")
            continue
        target.write_text(
            existing + ("\n" if existing.strip() else "") + CONVENTION_SECTION,
            encoding="utf-8")
        print(f"{name}: conventions injected")
    return 0


def _cmd_drift(args) -> int:
    from .drift import badge_state
    from .registry import load_entries

    repo = Path(args.repo).resolve()
    formulas = Path(args.formulas) if args.formulas else repo / "wiki" / "formulas"
    entries = load_entries(formulas)
    if not entries:
        print(f"scicodewiki: no entries under {formulas}", file=sys.stderr)
        return 2
    for entry in entries:
        print(f"{entry.id}: {badge_state(entry, repo)}")
    return 0


def _not_implemented(name: str) -> int:
    print(f"scicodewiki {name}: not implemented yet", file=sys.stderr)
    return 2


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="scicodewiki",
        description="Verified scientific documentation layer for "
                    "scientific computing repositories",
    )
    sub = parser.add_subparsers(dest="command")

    p = sub.add_parser("verify", help="run equivalence gates over registry entries")
    _repo_args(p)
    p.add_argument("--entry", help="verify a single entry id")
    p.add_argument("--seed", type=int, default=0,
                   help="holdout sampler seed (gate authority: fresh seed each run)")
    p.add_argument("--no-record", dest="record", action="store_false",
                   help="do not append verdicts (CI mode)")
    p.set_defaults(fn=_cmd_verify)

    p = sub.add_parser("serve", help="local wiki preview (mkdocs serve)")
    _repo_args(p)
    p.add_argument("-a", "--addr", default="127.0.0.1:8000")
    p.set_defaults(fn=_cmd_serve)

    p = sub.add_parser("build", help="render the wiki site")
    _repo_args(p)
    p.add_argument("--out", default=None,
                   help="output dir (default: <repo>/wiki)")
    p.set_defaults(fn=_cmd_build)

    p = sub.add_parser("drift", help="report badge states (verified/stale/failing/unverified)")
    _repo_args(p)
    p.set_defaults(fn=_cmd_drift)

    p = sub.add_parser("preview", help="zero-setup code-layer wiki from census (funnel entry, no LLM)")
    _repo_args(p)
    p.add_argument("--package", default=None)
    p.add_argument("--force", action="store_true",
                   help="overwrite an existing registry-backed wiki")
    p.set_defaults(fn=_cmd_preview)

    p = sub.add_parser("lint", help="mechanical discipline checks on narratives (chapter-spec as code)")
    _repo_args(p)
    p.set_defaults(fn=_cmd_lint)

    p = sub.add_parser("census", help="deterministic AST inventory of the package (decomposition ground truth)")
    _repo_args(p)
    p.add_argument("--package", default=None,
                   help="package dir name (default: repo dir name)")
    p.set_defaults(fn=_cmd_census)

    p = sub.add_parser("coverage", help="report census units no manifest stage documents")
    _repo_args(p)
    p.add_argument("--package", default=None)
    p.set_defaults(fn=_cmd_coverage)

    p = sub.add_parser("clean", help="delete generated wiki outputs (keep wiki/formulas inputs)")
    _repo_args(p)
    p.set_defaults(fn=_cmd_clean)

    p = sub.add_parser("on-edit", help="hook entrypoint: read hook JSON on stdin, gate bound entries")
    p.set_defaults(fn=lambda a: __import__(
        "scicodewiki.hookcheck", fromlist=["main"]).main())

    p = sub.add_parser("init", help="seed wiki/formulas/ in a target repo")
    _repo_args(p)
    p.add_argument("--agents-md", action="store_true",
                   help="opt in to AGENTS.md/CLAUDE.md convention injection "
                        "(off by default: footprint stays inside wiki/)")
    p.set_defaults(fn=_cmd_init)

    args = parser.parse_args(argv)
    if args.command is None:
        parser.print_help()
        return 0
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
